on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aviate-labs/setup-dfx@v0.2.3
        with:
          dfx-version: 0.12.1
          vessel-version: 0.6.3
      - run: |
          make check
